### ISSUE TITLE
Auto timer screens skin not taking effect

### ISSUE THREAD

**Issue by NoelOConnell** [kiddac/Enigma2_Skins#4]
Hi,

I'm using the slyk-1080-r19 skin.
It's a fresh install of OpenATV 6.4

The skins did not take effect for the Auto Timer screens (Viewing saved timers and adding a new timer).
All other screens were skinned correctly.

The workaround for this was to rename the `timers.xml` file to `timers1.xml` and update it in `skin.xml` also.
I read that worked for another user in a different forum and it worked for me also.

Just making a note of it here in case it helps others.

👍 for the skin, it's great.

**Comment by kiddac** [comment]
Filenames have been amended. Thanks
